// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravellioApi.DbContexts;

#nullable disable

namespace TravellioApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TravellioApi.Models.Entities.Accommodation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CheckIn")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("check_in");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("check_out");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("notes");

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("place_id");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_accommodations");

                    b.HasIndex("DestinationId")
                        .HasDatabaseName("ix_accommodations_destination_id");

                    b.ToTable("accommodations", (string)null);
                });

            modelBuilder.Entity("TravellioApi.Models.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("notes");

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("place_id");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<bool?>("TicketPurchased")
                        .HasColumnType("boolean")
                        .HasColumnName("ticket_purchased");

                    b.Property<bool?>("TicketRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("ticket_required");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_activities");

                    b.HasIndex("DestinationId")
                        .HasDatabaseName("ix_activities_destination_id");

                    b.ToTable("activities", (string)null);
                });

            modelBuilder.Entity("TravellioApi.Models.Entities.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Notes")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("notes");

                    b.Property<string>("PlaceId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("place_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_destinations");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_destinations_trip_id");

                    b.ToTable("destinations", (string)null);
                });

            modelBuilder.Entity("TravellioApi.Models.Entities.Leg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArrivalPlaceId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("arrival_place_id");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("arrival_time");

                    b.Property<string>("Company")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company");

                    b.Property<string>("DeparturePlaceId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("departure_place_id");

                    b.Property<DateTime?>("DepartureTime")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("departure_time");

                    b.Property<string>("Reservation")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("reservation");

                    b.Property<string>("Seat")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("seat");

                    b.Property<string>("ServiceNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("service_number");

                    b.Property<Guid>("TransportationId")
                        .HasColumnType("uuid")
                        .HasColumnName("transportation_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_legs");

                    b.HasIndex("TransportationId")
                        .HasDatabaseName("ix_legs_transportation_id");

                    b.ToTable("legs", (string)null);
                });

            modelBuilder.Entity("TravellioApi.Models.Entities.Transportation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArrivalDestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("arrival_destination_id");

                    b.Property<Guid?>("DepartureDestinationId")
                        .HasColumnType("uuid")
                        .HasColumnName("departure_destination_id");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_transportations");

                    b.HasIndex("ArrivalDestinationId")
                        .HasDatabaseName("ix_transportations_arrival_destination_id");

                    b.HasIndex("DepartureDestinationId")
                        .HasDatabaseName("ix_transportations_departure_destination_id");

                    b.HasIndex("TripId")
                        .HasDatabaseName("ix_transportations_trip_id");

                    b.ToTable("transportations", (string)null);
                });

            modelBuilder.Entity("TravellioApi.Models.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("HomePlaceId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("home_place_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_trips");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("TravellioApi.Models.Entities.Accommodation", b =>
                {
                    b.HasOne("TravellioApi.Models.Entities.Destination", null)
                        .WithMany("Accommodations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_accommodations_destinations_destination_id");

                    b.OwnsOne("TravellioApi.Models.Entities.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("AccommodationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(9, 2)
                                .HasColumnType("numeric(9,2)")
                                .HasColumnName("price_value");

                            b1.HasKey("AccommodationId");

                            b1.ToTable("accommodations");

                            b1.WithOwner()
                                .HasForeignKey("AccommodationId")
                                .HasConstraintName("fk_accommodations_accommodations_id");
                        });

                    b.Navigation("Price");
                });

            modelBuilder.Entity("TravellioApi.Models.Entities.Activity", b =>
                {
                    b.HasOne("TravellioApi.Models.Entities.Destination", null)
                        .WithMany("Activities")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activities_destinations_destination_id");

                    b.OwnsOne("TravellioApi.Models.Entities.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(9, 2)
                                .HasColumnType("numeric(9,2)")
                                .HasColumnName("price_value");

                            b1.HasKey("ActivityId");

                            b1.ToTable("activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId")
                                .HasConstraintName("fk_activities_activities_id");
                        });

                    b.Navigation("Price");
                });

            modelBuilder.Entity("TravellioApi.Models.Entities.Destination", b =>
                {
                    b.HasOne("TravellioApi.Models.Entities.Trip", null)
                        .WithMany("Destinations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_destinations_trips_trip_id");
                });

            modelBuilder.Entity("TravellioApi.Models.Entities.Leg", b =>
                {
                    b.HasOne("TravellioApi.Models.Entities.Transportation", null)
                        .WithMany("Legs")
                        .HasForeignKey("TransportationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_legs_transportations_transportation_id");

                    b.OwnsOne("TravellioApi.Models.Entities.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("LegId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(9, 2)
                                .HasColumnType("numeric(9,2)")
                                .HasColumnName("price_value");

                            b1.HasKey("LegId");

                            b1.ToTable("legs");

                            b1.WithOwner()
                                .HasForeignKey("LegId")
                                .HasConstraintName("fk_legs_legs_id");
                        });

                    b.Navigation("Price");
                });

            modelBuilder.Entity("TravellioApi.Models.Entities.Transportation", b =>
                {
                    b.HasOne("TravellioApi.Models.Entities.Destination", "Arrival")
                        .WithMany()
                        .HasForeignKey("ArrivalDestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_transportations_destinations_arrival_destination_id");

                    b.HasOne("TravellioApi.Models.Entities.Destination", "Departure")
                        .WithMany()
                        .HasForeignKey("DepartureDestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_transportations_destinations_departure_destination_id");

                    b.HasOne("TravellioApi.Models.Entities.Trip", null)
                        .WithMany("Transportations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transportations_trips_trip_id");

                    b.OwnsOne("TravellioApi.Models.Entities.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("TransportationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(9, 2)
                                .HasColumnType("numeric(9,2)")
                                .HasColumnName("price_value");

                            b1.HasKey("TransportationId");

                            b1.ToTable("transportations");

                            b1.WithOwner()
                                .HasForeignKey("TransportationId")
                                .HasConstraintName("fk_transportations_transportations_id");
                        });

                    b.Navigation("Arrival");

                    b.Navigation("Departure");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("TravellioApi.Models.Entities.Destination", b =>
                {
                    b.Navigation("Accommodations");

                    b.Navigation("Activities");
                });

            modelBuilder.Entity("TravellioApi.Models.Entities.Transportation", b =>
                {
                    b.Navigation("Legs");
                });

            modelBuilder.Entity("TravellioApi.Models.Entities.Trip", b =>
                {
                    b.Navigation("Destinations");

                    b.Navigation("Transportations");
                });
#pragma warning restore 612, 618
        }
    }
}
